---
title: "Сбор и аналитическая обработка информации о сетевом трафике"
author: Семёнова София БИСО-03-20
format: 
    md:
        output-file: readme.md
engine: knitr
---

# Лабораторная работа №2 сбор и аналитическая обработка информации о сетевом трафике

## Цель работы

1. Развить практические навыки использования современного стека инструментов сбора и аналитической обработки информации о сетвом трафике
2. Освоить базовые подходы блокировки нежелательного сетевого трафика
3. Закрепить знания о современных сетевых протоколах прикладного уровня

## Ход работы

1. С помощью Wireshark был собран сетевой трафик объёмом 146 Мб и записан в файл data.pcapng

2. С помощью Zeek была выделена метаинформация сетевого трафика (файл dns.log)

```{bash}
/opt/zeek/bin/zeek -C -r /home/sofiya/data.pcapng
```

3. Проанализируем полученный трафик:

Получим список нежелательных доменов:

```{bash}
curl https://winhelp2002.mvps.org/hosts.txt -o hosts
```

С помощью Python подготовим файл для анализа:

```{python}
bad_hosts = []
with open('hosts') as file:
    for line in file.readlines()[27:]:
        if line[0] == '#':
            continue
        bad_hosts.append(line.split()[1])
```

Преобразуем полученную метаинформацию в пригодный к анализу вид:

```{python}
hosts = []
with open('dns.log') as file:
    for line in file.readlines():
        if line[0] == '#':
            continue
        try:
            hosts.append(line.split()[9])
        except IndexError:
            continue
```

4. Посчитаем число вхождений DNS имен из списков в собранном трафике:

```{python}
bad_count = len([host for host in hosts if host in bad_hosts])
percentile = round(bad_count/len(hosts),3)*100
print("{} вхождений DNS в список нежелательного трафика.".format(str(bad_count)),
"Процент нежелательного трафика: {}%.".format(str(percentile)),sep='\n')
```

## Оценка результата

В результате проделанной работы мы смогли определить нежелательный трафик.

## Вывод

Таким образом, мы научились использовать современный стек инструментов для анализа сетевого трафика.