---
title: "Применение средств и методов OSINT"
author: Семёнова София БИСО-03-20
format: 
    md:
        output-file: readme.md
engine: knitr
---

# Лабораторная работа №6 Применение средств и методов OSINT

Собрать публичную информацию об Zecurion (вариант 13)

## Цель работы

1.  Освоить базовые подходы процессов OSINT
2.  Освоить современные инструменты поиска и сбора информации
3.  Освоить инструменты совместной работы в ходе аналитической деятельности

## План выполнения

1.  Собрать информацию о профильных компаниях в сфере ИБ и их продуктах
2.  Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.
3.  Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.
4.  Сформировать представление о рынке отечественных решений ИБ

## Ход работы

1.  Полное название компании

ООО "Зекурион Рус"

[Источник](https://www.rusprofile.ru/id/5887776)

2.  Структура компании

**Команда:**  Алексей Раевский - Генеральный директор  Александр Белявский - Коммерческий директор  Роман Васильев - Технический директор  Александр Ковалев - заместитель гендира

**Связь с отделами:**  Новым заказчикам - welcome\@zecurion.com\
Техподдержка - support\@zecurion.com\
Партнёрам - partners\@zecurion.com\
Журналистам и СМИ - pr\@zecurion.com\
ВУЗам и студентам - edu\@zecurion.com\
По общим вопросам - info\@zecurion.com

[Источник](https://zecurion.ru/company/)

3.  Основные направления деятельности

Основная деятельность Zecurion --- разработка систем защиты конфиденциальной информации от внутренних угроз. К основным компетенциям компании относятся:\
Защита информации от случайных и преднамеренных утечек\
Защита от бизнес-разведки и промышленного шпионажа\
Защита от несанкционированного доступа к данным\
Защита данных при хранении, использовании и уничтожении\
Защита от нарушения законодательства и отраслевых стандартов

**Продукты:**\
Data Loss Prevention - Защита от утечек информации и внутренних угроз\
Data-Centic Audit and Protection - Аналитика и защита данных\
Secure Web Gateway - Корпоративный прокси-сервер\
Storage Security - Защита данных при хранении, использовании и транспортировке

**Услуги:**\
Аудит и консалтинг ИБ\
Пилотный проект и ТЭО\
Разработка словарей

**Используемые технологии, языки программирования:**\
Системное программирование  Разработка программного обеспечения  Win32 API Многопоточность  Visual Studio  C++ stl  C++  Объектно-ориентированное проектирование

4.  Клиенты компании

Аэрофлот, Роснефть, Ростелеком, Allianz, Министерство обороны РФ, Сбер, Росгосстрах Банк, ВТБ пенсионный фонд, Башнефть, Пермский моторный завод ОДК, CenterCredit

5.  Основные веб-сайты компании и ее продуктов

https://zecurion.ru/ \
https://zecurion.com/products/ \
https://www.youtube.com/channel/UCuugH7AbSN-xJpW0h01iXFg

6.  Медиа

Мероприятия: SOC-форум 2021: переход к риск-менеджменту, роль DLP и актуальные угрозы [источник](https://zecurion.ru/soc-forum-2021-perehod-k-risk-menedzhmentu-rol-dlp-i-aktualnye-ugrozy/)

Контакты с прессой: Мария Разумовская - Руководитель пресс-службы - pr\@zecurion.com

Обзор DCAP-системы Zecurion: для упорядочения данных в корпоративной среде. [Источник](https://www.it-world.ru/cionews/security/190168.html)

7.  Уникальные достижения, ключевые продукты компании

В 2016 году выручка компании Zecurion составила 975 млн рублей, что на 37,1 % выше аналогичного показателя в 2015 году. В ранкинге "TAdviser100: Крупнейшие ИТ-компании в России" по итогам 2016 года компания Zecurion заняла 68-е место. [Источник](https://www.tadviser.ru/index.php/Компания:Zecurion_(ранее_SecurIT))

## Оценка результата

В ходе работы была изучена деятельность компании Zecurion на основе открытых источников, выделены продукция, сотрудники, достижения и др общая информация

## Вывод

В результате работы я ознакомилась с базовыми подходами OSINT, была получена информация о компании Zecurion.